#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if pip show drop2beets >/dev/null 2>&1; then
    plugins=$(beet config --default | shyaml get-value plugins)

    if [[ " $plugins " == *" drop2beets "* ]]; then
        if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
            exec \
                s6-setuidgid abc beet dropbox
        else
            exec \
                beet dropbox
        fi
    fi
fi
