#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# copy config
cp -n /defaults/beets.sh /config/beets.sh
cp -n /defaults/config.yaml /config/config.yaml

chmod +x /config/beets.sh

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    # permissions
    lsiown -R abc:abc \
        /config
fi
