#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8337" \
            s6-setuidgid abc beet web
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8337" \
            beet web
fi
